SimtechKursant: ProgramController Class Reference
ProgramController Class Reference
Controls programmin of a robot and running a program
Public Member Functions
void ConnectToRobot (Robot robot)
Allows to connect current robot to program
void AddInstruction (Instruction instruction)
Adds instruction to current program
void ChangePoint (Point point, int index)
Changes point on specified index
void RemoveInstruction (int index)
Removes selected instruction from a program at a given index
void InsertInstruction (Instruction instruction, int index)
Inserts instruction at specified index in a program
void RunProgram (bool isStep, bool looping=false)
Allows to run program using current robot
Instruction GetInstruction (int index)
Gets instruction from the list at speficed index
List< Instruction > GetInstructions ()
Gets list of all instructions in a program
void StopProgram ()
Stops the program without full stop
Private Member Functions
void Awake ()
Method run at the start of application Creates base for points used in instructions
void SendError (string error)
Sends error message to pendant to show at the top bar
IEnumerator RunningProgram ()
Coroutine allowing pogram to run
Private Attributes
List< Instruction > instructions = new List<Instruction>()
List of program instructions
List< Point > points = new List<Point>()
List of points used in movement of robot
int currentInstruction = 0
Current instruction index
bool loop = false
If true allows program to loop
Robot robot
Currently connected robot
bool running
Is the program currently running?
Detailed Description
Controls programmin of a robot and running a program
Member Function Documentation
AddInstruction()
void ProgramController.AddInstruction (Instruction instruction)
Adds instruction to current program
Parameters
instruction Instruction to add
References instructions, running, and SendError().
Awake()
void ProgramController.Awake () private
Method run at the start of application Creates base for points used in instructions
References Point, and points.
ChangePoint()
void ProgramController.ChangePoint (Point point, int index)
Changes point on specified index
Parameters
point Point to change to
index Index of a point in a list
References points, Point.position, and Point.rotation.
ConnectToRobot()
void ProgramController.ConnectToRobot (Robot robot)
Allows to connect current robot to program
Parameters
robot Robot to connect to
References Robot.GetHomePosition(), Robot.GetHomeRotation(), points, Point.position, robot, and Point.rotation.
GetInstruction()
Instruction ProgramController.GetInstruction (int index)
Gets instruction from the list at speficed index
Parameters
index Instruction at index
Returns
References instructions.
GetInstructions()
List<Instruction> ProgramController.GetInstructions ()
Gets list of all instructions in a program
Returns
Returns full list of all instructioons in a program
References instructions.
InsertInstruction()
void ProgramController.InsertInstruction (Instruction instruction, int index)
Inserts instruction at specified index in a program
Parameters
instruction Instruction to insert
index Index of inserted instruction
References Robot.GetCurrentPoint(), Robot.GetHomePosition(), instructions, points, Point.position, robot, Point.rotation, running, SendError(), and Instruction.type.
RemoveInstruction()
void ProgramController.RemoveInstruction (int index)
Removes selected instruction from a program at a given index
Parameters
index Index of an instruction
References instructions, running, and SendError().
RunningProgram()
IEnumerator ProgramController.RunningProgram () private
Coroutine allowing pogram to run
Returns
Waiting for next frame or timing the next instruction
References currentInstruction, instructions, loop, Robot.MoveToPoint(), points, Point.position, robot, Point.rotation, and running.
RunProgram()
void ProgramController.RunProgram (bool isStep, bool looping = false)
Allows to run program using current robot
Parameters
isStep Is the program in step mode?
looping Will the program loop itself?
References loop, running, RunningProgram(), and SendError().
SendError()
void ProgramController.SendError (string error) private
Sends error message to pendant to show at the top bar
Parameters
error Error to show
StopProgram()
void ProgramController.StopProgram ()
Stops the program without full stop
References Robot.ClearSequence(), loop, robot, and running.
Member Data Documentation
currentInstruction
int ProgramController.currentInstruction = 0 private
Current instruction index
instructions
List<Instruction> ProgramController.instructions = new List<Instruction>() private
List of program instructions
loop
bool ProgramController.loop = false private
If true allows program to loop
points
List<Point> ProgramController.points = new List<Point>() private
List of points used in movement of robot
robot
Robot ProgramController.robot private
Currently connected robot
running
bool ProgramController.running private
Is the program currently running?
The documentation for this class was generated from the following file:
D:/Git/SimtechKursant/Assets/Scripts/ProgramController.cs