SimtechKursant: LangController Class Reference
LangController Class Reference
Public Member Functions
void Initialize ()
void LangChange (string lang)
void GetByName (string name)
void Play ()
Public Attributes
AudioClip audioClip
string text
bool loaded
Private Member Functions
IEnumerator GetByNameCoroutine (string name)
Private Attributes
string lang = "pl_pl"
string path
XmlDocument xml
AudioSource audioSource
Member Function Documentation
GetByName()
void LangController.GetByName (string name)
References GetByNameCoroutine(), loaded, text, and xml.
GetByNameCoroutine()
IEnumerator LangController.GetByNameCoroutine (string name) private
References audioClip, loaded, path, and xml.
Initialize()
void LangController.Initialize ()
References audioSource, GetByName(), lang, LangChange(), and xml.
LangChange()
void LangController.LangChange (string lang)
References lang, path, and xml.
Play()
void LangController.Play ()
References audioClip, and audioSource.
Member Data Documentation
audioClip
AudioClip LangController.audioClip
audioSource
AudioSource LangController.audioSource private
lang
string LangController.lang = "pl_pl" private
loaded
bool LangController.loaded
path
string LangController.path private
text
string LangController.text
xml
XmlDocument LangController.xml private
The documentation for this class was generated from the following file:
D:/Git/SimtechKursant/Assets/Scripts/LangController.cs