SimtechKursant: Robot Class Reference
Robot Class Reference
Base class for a robot Contains full logic needed to control a single robot
Public Member Functions
Vector3 GetHomePosition ()
Home position helper method.
Vector3 GetHomeRotation ()
Home rotation helper method.
Point GetCurrentPoint ()
Get current point of end of a robot.
void MovePosition (MovementType type, MovementDirection direction, MovementContinuity continuity, float speed)
Switches robot to allow movement of robot end in direction with a specified type, direction, continuity and speed.
void MoveRotation (MovementType type, MovementDirection direction, MovementContinuity continuity, float speed)
Switches robot to allow rotation of robot end to rotation with a specified type, direction, continuity and speed.
void StopPositionMovement ()
Stops movement of a robot end
void StopRotationMovement ()
Stops rotation of a robot end
void SetManualOverride (bool manual)
Allows to swith to manual mode (change location of a robot end using hand)
void SetUserFrame (Transform frame)
Allows user to specify custom fream of reference for movement and rotation
void PushDeadMan (bool isRight, bool isOn)
Allows usage of dependency of pushed in deadman switches
void ShowTargetPoint (bool isOn)
Allows for visalisation of robot target
void SwitchToJoint (bool enable)
Switches manual movement of robot to joint and back
IEnumerator MoveToPoint (Vector3 position, Vector3 rotation, float speed, InstructionMovementType movementType)
Coroutine allowing robot to move using instructions
void ClearSequence ()
Clears the movement sequence containing position and rotation changes
Properties
float MaxMovementSpeed [get]
Accessor for maximum movement speed
float MaxRotationSpeed [get]
Accessor for maximum rotation speed
MovementType MovementType [get]
Accessor for movement type
Private Member Functions
void Start ()
Setup starting elements: Link robot to controller Set distance between base and end point for movement calculations Set home position and rotation for relative movement
void Update ()
Update method containing: Deadman switch - if any of deadman switches is off robot won't move If movement of position or rotation is requested robot will choose method according to type of movement
void FixedUpdate ()
Actual movmement of robot end is done in this method This is crucial for physics engine to correctly interpret joints and collisions
void MoveJoint (MovementDirection direction, float deltaTime, bool isRotation)
Allows robot to move in joint movement Direction of rotation is determined by parameters
void MovePositionBase (MovementDirection direction, float deltaTime)
Allows robot to move according to base reference point
void MovePositionTool (MovementDirection direction, float deltaTime)
Allows robot to move according to tool reference coordinates
void MoveRotation (MovementDirection direction, float deltaTime)
Allows robot to change tool rotation
void SetDecoyHierarchy (bool isJoined)
Sets decoy robot hirarchy Needed to count axes rotations
Private Attributes
GameObject robotEndPoint = default
The end point of a robot, usually at the base of a tool
GameObject referencePoint = default
Reference point for safe movement calculation
bool manualOverride = false
Switch for manual (hand) operations
Transform baseFrame = default
Transform of a base reference
Transform toolFrame = default
Transform for a tool frame
Transform userFrame = default
Transform for a user frame
TargetController targetController = default
Target controller reference
List< Transform > jointHierarchy = default
List of a joints that will be used to join them when using joint movement
Transform jointBase = default
Base of a joint movement
float maxMovementSpeed = 5f
Maximum speed of linear movement of an end point of a robot
float maxRotationSpeed = 35f
Maximum speed of rotation movement of a tool
Transform jointMoveEndPoint
End point of a decoy robot
List< Transform > decoyRobotJoints
Decoy robot hirarchy for joint instruction movement
Transform decoyBase
Base point for decoy robot
bool movePosition = false
Switch for position movement
bool moveRotation = false
Switch for rotation movement
bool jointMove = false
Switch for joint movement
float moveSpeed
Current movement speed
float rotationSpeed
Current rotation speed
MovementDirection positionDirection = default
Current position movement direction
MovementDirection rotationDirection = default
Current rotation direction
MovementType movementType = default
Current movement type
MovementContinuity movementContinuity = default
Current movement continuity
float defaultDistance = 0
Default distance from reference point to end point of a robot Used in safe movement of end point without detaching from robot
Vector3 lastPosition = Vector3.zero
Last position of end point used in correcting position
bool deadmanRightPushed = false
Bool for right deadman switch
bool deadmanLeftPushed = false
Bool for left deadman switch
Sequence movementToPoint
Sequence of movement of an instruction
Vector3 homePosition
Home position of a robot
Vector3 homeRotation
Home rotation of a robot
float jointMoveTimer = 0f
Time needed to complete joint move
float jointTraverseTime = 0f
Current joint movement time
List< Quaternion > jointBaseRotations = new List<Quaternion>()
Rotations of a joints for linear interpolation of axes
bool inJointMovement
Switch for checking if robot is in joint movement
Detailed Description
Base class for a robot Contains full logic needed to control a single robot
Member Function Documentation
ClearSequence()
void Robot.ClearSequence ()
Clears the movement sequence containing position and rotation changes
References movementToPoint.
FixedUpdate()
void Robot.FixedUpdate () private
Actual movmement of robot end is done in this method This is crucial for physics engine to correctly interpret joints and collisions
References decoyRobotJoints, defaultDistance, jointBaseRotations, jointHierarchy, jointMove, jointMoveTimer, jointTraverseTime, lastPosition, movePosition, moveRotation, referencePoint, and robotEndPoint.
GetCurrentPoint()
Point Robot.GetCurrentPoint ()
Get current point of end of a robot.
Returns
A Point structure containing position and rotation of end of a robot
References Point, and robotEndPoint.
GetHomePosition()
Vector3 Robot.GetHomePosition ()
Home position helper method.
Returns
Home (base) position
References homePosition.
GetHomeRotation()
Vector3 Robot.GetHomeRotation ()
Home rotation helper method.
Returns
Home (base) rotation
References homeRotation.
MoveJoint()
void Robot.MoveJoint (MovementDirection direction, float deltaTime, bool isRotation) private
Allows robot to move in joint movement Direction of rotation is determined by parameters
Parameters
direction Direction of rotation according to pendant buttons
deltaTime Delta time of a frame, allows for time-consistent rotation of joints
isRotation Determines if the pressed button is a rotation modifier (such as +X rot etc)
References jointHierarchy, and rotationSpeed.
MovePosition()
void Robot.MovePosition (MovementType type, MovementDirection direction, MovementContinuity continuity, float speed)
Switches robot to allow movement of robot end in direction with a specified type, direction, continuity and speed.
Parameters
type Base reference point for a move
direction Direction of a movement relative to the base reference point
continuity Continuity of movement
speed Speed of movement
References movementContinuity, movementType, movePosition, moveSpeed, and positionDirection.
MovePositionBase()
void Robot.MovePositionBase (MovementDirection direction, float deltaTime) private
Allows robot to move according to base reference point
Parameters
direction Direction of movement
deltaTime Delta time of a frame, allows for time-consistent movement
References baseFrame, movementContinuity, moveSpeed, TargetController.MoveTarget(), robotEndPoint, and targetController.
MovePositionTool()
void Robot.MovePositionTool (MovementDirection direction, float deltaTime) private
Allows robot to move according to tool reference coordinates
Parameters
direction Direction of movement
deltaTime Delta time of a frame, allows for time-consistent movement
References movementContinuity, moveSpeed, TargetController.MoveTarget(), robotEndPoint, targetController, and toolFrame.
MoveRotation() [1/2]
void Robot.MoveRotation (MovementDirection direction, float deltaTime) private
Allows robot to change tool rotation
Parameters
direction Direction of rotation
deltaTime Delta time of a frame, allows for time-consistent movement
References movementContinuity, TargetController.MoveRotation(), robotEndPoint, rotationDirection, rotationSpeed, targetController, and toolFrame.
MoveRotation() [2/2]
void Robot.MoveRotation (MovementType type, MovementDirection direction, MovementContinuity continuity, float speed)
Switches robot to allow rotation of robot end to rotation with a specified type, direction, continuity and speed.
Parameters
type Base reference point for a move
direction Direction of a rotation relative to the base reference point
continuity Continuity of rotation
speed Speed of rotation
References movementContinuity, movementType, moveRotation, rotationDirection, and rotationSpeed.
MoveToPoint()
IEnumerator Robot.MoveToPoint (Vector3 position, Vector3 rotation, float speed, InstructionMovementType movementType)
Coroutine allowing robot to move using instructions
Parameters
position Target position
rotation Target rotation
speed Speed of movement
movementType Type of moevement
Returns
References decoyRobotJoints, jointBaseRotations, jointHierarchy, jointMove, jointMoveEndPoint, jointTraverseTime, maxRotationSpeed, movementToPoint, movementType, robotEndPoint, SetDecoyHierarchy(), and SwitchToJoint().
PushDeadMan()
void Robot.PushDeadMan (bool isRight, bool isOn)
Allows usage of dependency of pushed in deadman switches
Parameters
isRight Is the used switch is right switch?
isOn Is the switch on or off?
References deadmanLeftPushed, and deadmanRightPushed.
SetDecoyHierarchy()
void Robot.SetDecoyHierarchy (bool isJoined) private
Sets decoy robot hirarchy Needed to count axes rotations
Parameters
isJoined Is the decoy in joint movement?
References decoyBase, and decoyRobotJoints.
SetManualOverride()
void Robot.SetManualOverride (bool manual)
Allows to swith to manual mode (change location of a robot end using hand)
Parameters
manual Is manual mode switched on or off?
References manualOverride.
SetUserFrame()
void Robot.SetUserFrame (Transform frame)
Allows user to specify custom fream of reference for movement and rotation
Parameters
frame Transform on a custom frame
References userFrame.
ShowTargetPoint()
void Robot.ShowTargetPoint (bool isOn)
Allows for visalisation of robot target
Parameters
isOn Is the target on or off?
References TargetController.ShowTarget(), and targetController.
Start()
void Robot.Start () private
Setup starting elements: Link robot to controller Set distance between base and end point for movement calculations Set home position and rotation for relative movement
References defaultDistance, homePosition, homeRotation, lastPosition, referencePoint, and robotEndPoint.
StopPositionMovement()
void Robot.StopPositionMovement ()
Stops movement of a robot end
References movePosition.
StopRotationMovement()
void Robot.StopRotationMovement ()
Stops rotation of a robot end
References moveRotation.
SwitchToJoint()
void Robot.SwitchToJoint (bool enable)
Switches manual movement of robot to joint and back
Parameters
enable Is joint movement enabled?
References inJointMovement, jointBase, and jointHierarchy.
Update()
void Robot.Update () private
Update method containing: Deadman switch - if any of deadman switches is off robot won't move If movement of position or rotation is requested robot will choose method according to type of movement
References deadmanLeftPushed, deadmanRightPushed, inJointMovement, MoveJoint(), movementType, movePosition, MovePositionBase(), MovePositionTool(), moveRotation, MoveRotation(), positionDirection, rotationDirection, and SwitchToJoint().
Member Data Documentation
baseFrame
Transform Robot.baseFrame = default private
Transform of a base reference
deadmanLeftPushed
bool Robot.deadmanLeftPushed = false private
Bool for left deadman switch
deadmanRightPushed
bool Robot.deadmanRightPushed = false private
Bool for right deadman switch
decoyBase
Transform Robot.decoyBase private
Base point for decoy robot
decoyRobotJoints
List<Transform> Robot.decoyRobotJoints private
Decoy robot hirarchy for joint instruction movement
defaultDistance
float Robot.defaultDistance = 0 private
Default distance from reference point to end point of a robot Used in safe movement of end point without detaching from robot
homePosition
Vector3 Robot.homePosition private
Home position of a robot
homeRotation
Vector3 Robot.homeRotation private
Home rotation of a robot
inJointMovement
bool Robot.inJointMovement private
Switch for checking if robot is in joint movement
jointBase
Transform Robot.jointBase = default private
Base of a joint movement
jointBaseRotations
List<Quaternion> Robot.jointBaseRotations = new List<Quaternion>() private
Rotations of a joints for linear interpolation of axes
jointHierarchy
List<Transform> Robot.jointHierarchy = default private
List of a joints that will be used to join them when using joint movement
jointMove
bool Robot.jointMove = false private
Switch for joint movement
jointMoveEndPoint
Transform Robot.jointMoveEndPoint private
End point of a decoy robot
jointMoveTimer
float Robot.jointMoveTimer = 0f private
Time needed to complete joint move
jointTraverseTime
float Robot.jointTraverseTime = 0f private
Current joint movement time
lastPosition
Vector3 Robot.lastPosition = Vector3.zero private
Last position of end point used in correcting position
manualOverride
bool Robot.manualOverride = false private
Switch for manual (hand) operations
maxMovementSpeed
float Robot.maxMovementSpeed = 5f private
Maximum speed of linear movement of an end point of a robot
maxRotationSpeed
float Robot.maxRotationSpeed = 35f private
Maximum speed of rotation movement of a tool
movementContinuity
MovementContinuity Robot.movementContinuity = default private
Current movement continuity
movementToPoint
Sequence Robot.movementToPoint private
Sequence of movement of an instruction
movementType
MovementType Robot.movementType = default private
Current movement type
movePosition
bool Robot.movePosition = false private
Switch for position movement
moveRotation
bool Robot.moveRotation = false private
Switch for rotation movement
moveSpeed
float Robot.moveSpeed private
Current movement speed
positionDirection
MovementDirection Robot.positionDirection = default private
Current position movement direction
referencePoint
GameObject Robot.referencePoint = default private
Reference point for safe movement calculation
robotEndPoint
GameObject Robot.robotEndPoint = default private
The end point of a robot, usually at the base of a tool
rotationDirection
MovementDirection Robot.rotationDirection = default private
Current rotation direction
rotationSpeed
float Robot.rotationSpeed private
Current rotation speed
targetController
TargetController Robot.targetController = default private
Target controller reference
toolFrame
Transform Robot.toolFrame = default private
Transform for a tool frame
userFrame
Transform Robot.userFrame = default private
Transform for a user frame
Property Documentation
MaxMovementSpeed
float Robot.MaxMovementSpeed get
Accessor for maximum movement speed
MaxRotationSpeed
float Robot.MaxRotationSpeed get
Accessor for maximum rotation speed
MovementType
MovementType Robot.MovementType get
Accessor for movement type
The documentation for this class was generated from the following file:
D:/Git/SimtechKursant/Assets/Scripts/Robot.cs