SimtechKursant: RobotController Class Reference
RobotController Class Reference
Controls logic for controlling a robot as a single entity
Public Member Functions
void SetMovementType (MovementType type)
Sets desired movement type of robot
void SetMovementContinuity (int continuity)
Sets desired movement continuity type
void ChangeRobotSpeed (bool up)
Changes robot speed up or down
void LinkRobot (Robot robot)
Links robot to controller
void LinkPendant (PendantController pendant)
Links pendant to controller
void MovePosition (int direction)
Moves robot end point in specified direction
void MoveRotation (int direction)
Rotates robot end point in specified direction
void StopMovingPosition ()
Stops moving position of a robot end point
void StopMovingRotation ()
Stops rotation of a robot end point
void SwitchLeftDeadman (bool isOn)
Switches state of a left deadman
void SwitchRightDeadman (bool isOn)
Switches state of a right deadman
void CycleCoordinateSystem ()
Changes coordinate system between all the options in MovementType
void SwitchToJoint (bool isOn)
Switches curent robot to joint movement
Properties
MovementType MovementType [get]
Public accessor for movement type
MovementContinuity MovementContinuity [get]
Public acessor for movement continuity
Private Attributes
MovementType movementType = default
Type of movement of a robot
MovementContinuity movementContinuity = default
Continuity of a movement of a robot
float robotSpeed = 0.1f
Speed of a robot
Robot robot = default
Currently controlled robot
PendantController pendant = default
Connected pendant
ProgramController program = default
Connected program controller
Detailed Description
Controls logic for controlling a robot as a single entity
Member Function Documentation
ChangeRobotSpeed()
void RobotController.ChangeRobotSpeed (bool up)
Changes robot speed up or down
Parameters
up Is the speed changing up?
References PendantController.ChangeMovementSpeed(), pendant, and robotSpeed.
CycleCoordinateSystem()
void RobotController.CycleCoordinateSystem ()
Changes coordinate system between all the options in MovementType
References movementType, and SetMovementType().
LinkPendant()
void RobotController.LinkPendant (PendantController pendant)
Links pendant to controller
Parameters
pendant Pendant to link
References pendant.
LinkRobot()
void RobotController.LinkRobot (Robot robot)
Links robot to controller
Parameters
robot Robot to link
References ProgramController.ConnectToRobot(), program, and robot.
MovePosition()
void RobotController.MovePosition (int direction)
Moves robot end point in specified direction
Parameters
direction Integer number for direction (see MovementDirection)
References Robot.MaxMovementSpeed, movementContinuity, movementType, Robot.MovePosition(), robot, and robotSpeed.
MoveRotation()
void RobotController.MoveRotation (int direction)
Rotates robot end point in specified direction
Parameters
direction Integer number for rotation direction (see MovementDirection)
References Robot.MaxRotationSpeed, movementContinuity, movementType, Robot.MoveRotation(), robot, and robotSpeed.
SetMovementContinuity()
void RobotController.SetMovementContinuity (int continuity)
Sets desired movement continuity type
Parameters
continuity Chosen movement continuity
References movementContinuity, MovementContinuity, robot, and Robot.ShowTargetPoint().
SetMovementType()
void RobotController.SetMovementType (MovementType type)
Sets desired movement type of robot
Parameters
type Chosen movement type
References PendantController.ChangeMovementType(), movementType, pendant, and SwitchToJoint().
StopMovingPosition()
void RobotController.StopMovingPosition ()
Stops moving position of a robot end point
References robot, and Robot.StopPositionMovement().
StopMovingRotation()
void RobotController.StopMovingRotation ()
Stops rotation of a robot end point
References robot, and Robot.StopRotationMovement().
SwitchLeftDeadman()
void RobotController.SwitchLeftDeadman (bool isOn)
Switches state of a left deadman
Parameters
isOn Is the daedman switch on?
References Robot.PushDeadMan(), and robot.
SwitchRightDeadman()
void RobotController.SwitchRightDeadman (bool isOn)
Switches state of a right deadman
Parameters
isOn Is the daedman switch on?
References Robot.PushDeadMan(), and robot.
SwitchToJoint()
void RobotController.SwitchToJoint (bool isOn)
Switches curent robot to joint movement
Parameters
isOn Is the robot switched to joint movement?
References robot, and Robot.SwitchToJoint().
Member Data Documentation
movementContinuity
MovementContinuity RobotController.movementContinuity = default private
Continuity of a movement of a robot
movementType
MovementType RobotController.movementType = default private
Type of movement of a robot
pendant
PendantController RobotController.pendant = default private
Connected pendant
program
ProgramController RobotController.program = default private
Connected program controller
robot
Robot RobotController.robot = default private
Currently controlled robot
robotSpeed
float RobotController.robotSpeed = 0.1f private
Speed of a robot
Property Documentation
MovementContinuity
MovementContinuity RobotController.MovementContinuity get
Public acessor for movement continuity
MovementType
MovementType RobotController.MovementType get
Public accessor for movement type
The documentation for this class was generated from the following file:
D:/Git/SimtechKursant/Assets/Scripts/RobotController.cs