SimtechKursant: Module1Step4 Class Reference
Module1Step4 Class Reference
Step 4 of module 1
Public Member Functions
void SetTutorialTextAndUnlock ()
Show first tutorial text and unlock next intruction
void CheckRightHand ()
Has the righ hand been activated? If so start counting time
void ResetCounterForRightHand ()
Reset counting time fot right hand
void LateUpdate ()
Check if any key has been pressed when second part has been shown
Private Member Functions
IEnumerator Unlock ()
Unlock second instruction after a time
IEnumerator CheckRightHandCor ()
Start counting right hand time
void ShowSecondPart ()
Show second part of tutorial
Private Attributes
bool shownSecondText = false
Was the second text shwown already?
bool unlocked = false
Is next instruction unlocked?
GameObject rightHand = default
Right hand object
GameObject rightHandChecker = default
Checker to hlad right hand data
Additional Inherited Members
Public Attributes inherited from Step
UnityEvent OnStepStart
Events called at the start of a step
UnityEvent OnStepEnd
Events called ath the end of the step
Detailed Description
Step 4 of module 1
Member Function Documentation
CheckRightHand()
void Module1Step4.CheckRightHand ()
Has the righ hand been activated? If so start counting time
References CheckRightHandCor(), and unlocked.
CheckRightHandCor()
IEnumerator Module1Step4.CheckRightHandCor () private
Start counting right hand time
Returns
References rightHand, and ShowSecondPart().
LateUpdate()
void Module1Step4.LateUpdate ()
Check if any key has been pressed when second part has been shown
References InputController.isAnyKeyDown(), shownSecondText, and unlocked.
ResetCounterForRightHand()
void Module1Step4.ResetCounterForRightHand ()
Reset counting time fot right hand
SetTutorialTextAndUnlock()
void Module1Step4.SetTutorialTextAndUnlock ()
Show first tutorial text and unlock next intruction
References rightHand, rightHandChecker, and Unlock().
ShowSecondPart()
void Module1Step4.ShowSecondPart () private
Show second part of tutorial
References shownSecondText, Unlock(), and unlocked.
Unlock()
IEnumerator Module1Step4.Unlock () private
Unlock second instruction after a time
Returns
Wait for half a second
References unlocked.
Member Data Documentation
rightHand
GameObject Module1Step4.rightHand = default private
Right hand object
rightHandChecker
GameObject Module1Step4.rightHandChecker = default private
Checker to hlad right hand data
shownSecondText
bool Module1Step4.shownSecondText = false private
Was the second text shwown already?
unlocked
bool Module1Step4.unlocked = false private
Is next instruction unlocked?
The documentation for this class was generated from the following file:
D:/Git/SimtechKursant/Assets/Scripts/Module1/Module1Step4.cs