SimtechKursant: ConnectionController Class Reference
ConnectionController Class Reference
Controller for connection control including server listening and message sending
Public Member Functions
void ConnectToServerApplication ()
Main method used to searching and connecting to server
bool IsConnected ()
Is client connected to server?
void SendModuleChange (int module)
Sends message to server indicating change in module number
void SendStepChange (int step)
Sends message to server indicating change in step number
void SignalModuleFinished ()
Sends message to server that a module is finished by user
void RequestAssistance ()
Sends message to server that user need assistance
Public Attributes
Action< string > OnMessageRecieved = null
Callback used when receiving message from server
Private Member Functions
void SearchForServer (UnityEvent callback)
Look up servers on local network and use callback when finished For debug purposes we currently are connecting to localhost
void ConnectToServer (IPAddress ip, ushort port=4296)
Allows to connect to specified server by ip and port
void ProcessMessage (object sender, MessageReceivedEventArgs e)
Process message sent by server
void SetUpStream ()
Start stream for server
void ResetConnectedState ()
Reset connected state when disconnecting
Private Attributes
UnityClient client = default
Client used to connect to server
bool connected
Is client currently connected?
StreamController streamController = default
Stream controller used to create and send cemara data
UnityEvent OnFinishedLookup = new UnityEvent()
Callback used when finishing search for server
UnityEvent OnDisconnected = new UnityEvent()
Callback used when disconnecting from server
IPAddress serverIP
Current server IP
Detailed Description
Controller for connection control including server listening and message sending
Member Function Documentation
ConnectToServer()
void ConnectionController.ConnectToServer (IPAddress ip, ushort port = 4296) private
Allows to connect to specified server by ip and port
Parameters
ip IP of thje server to connect to
port Port of the server
References client, connected, OnDisconnected, ProcessMessage(), ResetConnectedState(), and SetUpStream().
ConnectToServerApplication()
void ConnectionController.ConnectToServerApplication ()
Main method used to searching and connecting to server
References ConnectToServer(), OnFinishedLookup, SearchForServer(), and serverIP.
IsConnected()
bool ConnectionController.IsConnected ()
Is client connected to server?
Returns
Bool indicating if client is connected to server
References connected.
ProcessMessage()
void ConnectionController.ProcessMessage (object sender, MessageReceivedEventArgs e) private
Process message sent by server
Parameters
sender Sender object
e Arguments of a message
References OnMessageRecieved.
RequestAssistance()
void ConnectionController.RequestAssistance ()
Sends message to server that user need assistance
References client.
ResetConnectedState()
void ConnectionController.ResetConnectedState () private
Reset connected state when disconnecting
References connected.
SearchForServer()
void ConnectionController.SearchForServer (UnityEvent callback) private
Look up servers on local network and use callback when finished For debug purposes we currently are connecting to localhost
Parameters
callback Callback method to call when finished lookup
References client, and serverIP.
SendModuleChange()
void ConnectionController.SendModuleChange (int module)
Sends message to server indicating change in module number
Parameters
module Number of a module to send
References client.
SendStepChange()
void ConnectionController.SendStepChange (int step)
Sends message to server indicating change in step number
Parameters
step Number of a step to send
References client.
SetUpStream()
void ConnectionController.SetUpStream () private
Start stream for server
References StreamController.SetUpSending(), and streamController.
SignalModuleFinished()
void ConnectionController.SignalModuleFinished ()
Sends message to server that a module is finished by user
References client.
Member Data Documentation
client
UnityClient ConnectionController.client = default private
Client used to connect to server
connected
bool ConnectionController.connected private
Is client currently connected?
OnDisconnected
UnityEvent ConnectionController.OnDisconnected = new UnityEvent() private
Callback used when disconnecting from server
OnFinishedLookup
UnityEvent ConnectionController.OnFinishedLookup = new UnityEvent() private
Callback used when finishing search for server
OnMessageRecieved
Action<string> ConnectionController.OnMessageRecieved = null
Callback used when receiving message from server
serverIP
IPAddress ConnectionController.serverIP private
Current server IP
streamController
StreamController ConnectionController.streamController = default private
Stream controller used to create and send cemara data
The documentation for this class was generated from the following file:
D:/Git/SimtechKursant/Assets/Scripts/ConnectionController.cs