SimtechKursant: FlowController Class Reference
FlowController Class Reference
Main flow controller for application, manages other controllers
Private Member Functions
void OnApplicationStart ()
Sets up every controller at the start of an application
void OnApplicationExit ()
Executes methods when appication should quit
void Start ()
Executes when application starts
void OnApplicationQuit ()
Executes when application quits
void SetUpBindings ()
Set up bindings for interactions
void ProcessMessage (string data)
Allows to process messages sent from server
void Update ()
Debug method to use to signal finished module
Private Attributes
ModuleController moduleController = default
Reference to module controller object
SettingsController settingsController = default
Reference to settings controller object
ConnectionController connectionController = default
Reference to connection controller object
InputController inputController = default
Reference to input controller object
AnalyticsController analyticsController = default
Reference to analytics controller object
UIController uiController = default
Reference to UI controller object
Detailed Description
Main flow controller for application, manages other controllers
Member Function Documentation
OnApplicationExit()
void FlowController.OnApplicationExit () private
Executes methods when appication should quit
References analyticsController, AnalyticsController.SaveData(), SettingsController.SaveSettings(), and settingsController.
OnApplicationQuit()
void FlowController.OnApplicationQuit () private
Executes when application quits
References OnApplicationExit().
OnApplicationStart()
void FlowController.OnApplicationStart () private
Sets up every controller at the start of an application
References connectionController, ConnectionController.ConnectToServerApplication(), SettingsController.LoadSettings(), moduleController, ConnectionController.OnMessageRecieved, ProcessMessage(), ModuleController.RunModule(), and settingsController.
ProcessMessage()
void FlowController.ProcessMessage (string data) private
Allows to process messages sent from server
Parameters
data Data from message sent by server
References ModuleController.GetCurrentModule(), moduleController, ModuleController.NextModule(), ModuleController.RunModule(), Module.RunStep(), UIController.SetWatchingIndicator(), and uiController.
SetUpBindings()
void FlowController.SetUpBindings () private
Set up bindings for interactions
References inputController, and InputController.ProcessBindings().
Start()
void FlowController.Start () private
Executes when application starts
References OnApplicationStart().
Update()
void FlowController.Update () private
Debug method to use to signal finished module
References moduleController, and ModuleController.SignalModuleFinished().
Member Data Documentation
analyticsController
AnalyticsController FlowController.analyticsController = default private
Reference to analytics controller object
connectionController
ConnectionController FlowController.connectionController = default private
Reference to connection controller object
inputController
InputController FlowController.inputController = default private
Reference to input controller object
moduleController
ModuleController FlowController.moduleController = default private
Reference to module controller object
settingsController
SettingsController FlowController.settingsController = default private
Reference to settings controller object
uiController
UIController FlowController.uiController = default private
Reference to UI controller object
The documentation for this class was generated from the following file:
D:/Git/SimtechKursant/Assets/Scripts/FlowController.cs