SimtechKursant: PendantController Class Reference
PendantController Class Reference
Maintains logic of a pendant
Public Member Functions
void SetupBinds ()
Sets up input to allow interaction with pendant
void ChangeMovementSpeed (float speed)
Changes text of movement speed on screen
void ChangeMovementType (MovementType type)
Changes text of movement type on screen
void ShowMessage (string message)
Shows message sent by trainer
void CloseMessage ()
Closes message box
void UpdateMainProgram (List< Instruction > instructions)
Parses program text into pendant screen
void ChangeInstructionIndex (bool up)
Change currently selected instruction index
void ChangeInstructionIndex (int index)
Change currently selected instruction index to specified index
void RemoveInstruction ()
Removes currently selected instruction from program
void StopProgram ()
Stops program execution
void StartProgram ()
Starts running program
void ShowInstructionList (bool isInserting)
Shows instruction list and unbinds interactions with program
void InsertInstruction (Instruction instruction)
Inserts instruction at the selected index of instruction
void ShowError (string error)
Shows error on top bar on screen
void SelectPart (bool goRight)
Changes selected part of an instruction
void ProcessInputOnInstruction (string input)
Sends input to instruction for processing
void UseButton (bool press)
Debug method for usage of buttons using gamepad
Private Member Functions
void Start ()
Connects controller to a robot Sets up message flow Activates binds allowing to interact with pendant
void Unbind ()
Unbinds all binds activated by this entity
void LinkToRobotController ()
Links to robot allowing control of it
void GetInstruction (int index)
Gets instruction of specified index from program to cached variable
void UpdateIndexVisual ()
Allows change of selected instruction
void SelectText (int startIndex, int endIndex)
Marks seleceted part of an instruction
IEnumerator DelayedInit ()
Delays initialization of markdown for full program parsing
Private Attributes
RobotController robotController = default
Connected robot controller
TextMeshProUGUI movementSpeed = default
Robot movement speed shown on a pendant screen
TextMeshProUGUI movementType = default
Robot movement type shown on a pendant screen
PendantVisualizer visualizer = default
Visualizer needed for gampead and keyboard cursor selection of buttons
GameObject messageBox = default
Message box available on a pendant, shows messages from trainer
TextMeshProUGUI programText = default
Program text shown on a pendant screen
TextMeshProUGUI programSelectText = default
Alternative text used for markdown of instructions and parts
TextMeshProUGUI errorText = default
Error text shown at the top of the pendant screen
GameObject instructionList = default
List of all the instructions shown on a pendant
List< InputBind > binds = new List<InputBind>()
Binds to interact with a pendant
int instructionIndex = 1
Currently selected instruction index
Instruction currentInstruction = default
Currently selected instruction
string currentText = default
Text of a program withour markdowns
int instructionCount = default
Count of instructions in a program, safelock for selection
int selectedPart = 0
Currently selected part of an instruction
int textStartIndex = 0
Starting index of an instruction text
List< string > errorList = new List<string>()
Shown errors list for lookup
Detailed Description
Maintains logic of a pendant
Member Function Documentation
ChangeInstructionIndex() [1/2]
void PendantController.ChangeInstructionIndex (bool up)
Change currently selected instruction index
Parameters
up Should the counter go up?
References GetInstruction(), instructionCount, instructionIndex, and UpdateIndexVisual().
ChangeInstructionIndex() [2/2]
void PendantController.ChangeInstructionIndex (int index)
Change currently selected instruction index to specified index
Parameters
index Index of an instruction
References GetInstruction(), instructionIndex, and UpdateIndexVisual().
ChangeMovementSpeed()
void PendantController.ChangeMovementSpeed (float speed)
Changes text of movement speed on screen
Parameters
speed Current speed of a robot
References movementSpeed.
ChangeMovementType()
void PendantController.ChangeMovementType (MovementType type)
Changes text of movement type on screen
Parameters
type Current type of a robot movement
References movementType.
CloseMessage()
void PendantController.CloseMessage ()
Closes message box
References messageBox.
DelayedInit()
IEnumerator PendantController.DelayedInit () private
Delays initialization of markdown for full program parsing
Returns
Delay before selecting
References ChangeInstructionIndex().
GetInstruction()
void PendantController.GetInstruction (int index) private
Gets instruction of specified index from program to cached variable
Parameters
index
References currentInstruction.
InsertInstruction()
void PendantController.InsertInstruction (Instruction instruction)
Inserts instruction at the selected index of instruction
Parameters
instruction Instruction to insert
References GetInstruction(), instructionIndex, and SelectPart().
LinkToRobotController()
void PendantController.LinkToRobotController () private
Links to robot allowing control of it
References RobotController.LinkPendant(), and robotController.
ProcessInputOnInstruction()
void PendantController.ProcessInputOnInstruction (string input)
Sends input to instruction for processing
Parameters
input Inputted sequence
References currentInstruction, Instruction.ProcessInput(), selectedPart, Instruction.SelectPart(), SelectText(), textStartIndex, and UpdateMainProgram().
RemoveInstruction()
void PendantController.RemoveInstruction ()
Removes currently selected instruction from program
References GetInstruction(), instructionIndex, selectedPart, and SelectPart().
SelectPart()
void PendantController.SelectPart (bool goRight)
Changes selected part of an instruction
Parameters
goRight Should select next part?
References currentInstruction, selectedPart, Instruction.SelectPart(), SelectText(), textStartIndex, and Instruction.type.
SelectText()
void PendantController.SelectText (int startIndex, int endIndex) private
Marks seleceted part of an instruction
Parameters
startIndex Stating index of markdown
endIndex Ending index of a markdown
References currentText, programSelectText, and programText.
SetupBinds()
void PendantController.SetupBinds ()
Sets up input to allow interaction with pendant
References binds.
ShowError()
void PendantController.ShowError (string error)
Shows error on top bar on screen
Parameters
error Text of an error
References errorList, and errorText.
ShowInstructionList()
void PendantController.ShowInstructionList (bool isInserting)
Shows instruction list and unbinds interactions with program
Parameters
isInserting SHould the new instruction be inserted or changed?
References instructionList, and Unbind().
ShowMessage()
void PendantController.ShowMessage (string message)
Shows message sent by trainer
Parameters
message String containing message
References messageBox.
Start()
void PendantController.Start () private
Connects controller to a robot Sets up message flow Activates binds allowing to interact with pendant
References DelayedInit(), LinkToRobotController(), SetupBinds(), and ShowMessage().
StartProgram()
void PendantController.StartProgram ()
Starts running program
StopProgram()
void PendantController.StopProgram ()
Stops program execution
Unbind()
void PendantController.Unbind () private
Unbinds all binds activated by this entity
References binds, and InputBind.inputName.
UpdateIndexVisual()
void PendantController.UpdateIndexVisual () private
Allows change of selected instruction
References currentInstruction, currentText, instructionIndex, Instruction.selectedPart, selectedPart, SelectText(), and textStartIndex.
UpdateMainProgram()
void PendantController.UpdateMainProgram (List< Instruction > instructions)
Parses program text into pendant screen
Parameters
instructions List of instructions in a program
References currentText, instructionCount, Instruction.ParseInstruction(), programSelectText, and programText.
UseButton()
void PendantController.UseButton (bool press)
Debug method for usage of buttons using gamepad
Parameters
press Is button pressed or depressed?
References PendantVisualizer.GetSelectedButton(), and visualizer.
Member Data Documentation
binds
List<InputBind> PendantController.binds = new List<InputBind>() private
Binds to interact with a pendant
currentInstruction
Instruction PendantController.currentInstruction = default private
Currently selected instruction
currentText
string PendantController.currentText = default private
Text of a program withour markdowns
errorList
List<string> PendantController.errorList = new List<string>() private
Shown errors list for lookup
errorText
TextMeshProUGUI PendantController.errorText = default private
Error text shown at the top of the pendant screen
instructionCount
int PendantController.instructionCount = default private
Count of instructions in a program, safelock for selection
instructionIndex
int PendantController.instructionIndex = 1 private
Currently selected instruction index
instructionList
GameObject PendantController.instructionList = default private
List of all the instructions shown on a pendant
messageBox
GameObject PendantController.messageBox = default private
Message box available on a pendant, shows messages from trainer
movementSpeed
TextMeshProUGUI PendantController.movementSpeed = default private
Robot movement speed shown on a pendant screen
movementType
TextMeshProUGUI PendantController.movementType = default private
Robot movement type shown on a pendant screen
programSelectText
TextMeshProUGUI PendantController.programSelectText = default private
Alternative text used for markdown of instructions and parts
programText
TextMeshProUGUI PendantController.programText = default private
Program text shown on a pendant screen
robotController
RobotController PendantController.robotController = default private
Connected robot controller
selectedPart
int PendantController.selectedPart = 0 private
Currently selected part of an instruction
textStartIndex
int PendantController.textStartIndex = 0 private
Starting index of an instruction text
visualizer
PendantVisualizer PendantController.visualizer = default private
Visualizer needed for gampead and keyboard cursor selection of buttons
The documentation for this class was generated from the following file:
D:/Git/SimtechKursant/Assets/Scripts/PendantController.cs